### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by passiw** [EliasKotlyar/MQB-SteeringWheel#1]
Hi Elias, ich wohne auch in München und ein Freund von Volodymyr (das ist der Autor des git für den MQB-steering-wheel-adapter, den du geforked hast). Da wir glaube ich etwas ähnliches vorhaben, würde ich mich freuen über eine Mail an [removed] :-)

**Comment by EliasKotlyar** [comment]
Hallo Pascal,

Habe dir soeben eine Email geschrieben

Grüße
Elias
